name: CI

on: push

env:
  BINARY_NAME: resource-checker

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.7'
      - name: Install dependencies
        run: make install
      - name: Run lint check
        run: make lint
      - name: Run build
        run: |
          GOOS=linux GOARCH=amd64 go build -o build/${BINARY_NAME}-linux-x86_64 checker.go
          GOOS=linux GOARCH=arm64 go build -o build/${BINARY_NAME}-linux-aarch64 checker.go
          GOOS=linux GOARCH=arm go build -o build/${BINARY_NAME}-linux-armv7l checker.go
          GOOS=darwin GOARCH=amd64 go build -o build/${BINARY_NAME}-darwin-x86_64 checker.go
          GOOS=darwin GOARCH=arm64 go build -o build/${BINARY_NAME}-darwin-aarch64 checker.go
          GOOS=windows GOARCH=amd64 go build -o build/${BINARY_NAME}-windows-x86_64.exe checker.go
      - name: Create artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BINARY_NAME }}-binaries
          path: build/

  release:
    if: startsWith(github.ref, 'refs/tags')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download binaries artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.BINARY_NAME }}-binaries
          path: build/
      - name: Uploaded binaries as release assets
        run: |
          set -x
          tag_name="${GITHUB_REF##*/}"
          assets=()
          for binary in ./build/*; do
            assets+=("-a" "${binary}")
          done
          hub release edit "${assets[@]}" -m "$tag_name" "$tag_name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
